### ISSUE TITLE
WHat happened to Rogue?

### ISSUE THREAD

**Issue by TheTechRobo** [knarkzel/ogc-engine#1]
Seemingly overnight the repo for rogue got deleted.

**Comment by lambdachad** [comment]
The repository has been turned into examples for `ogc-engine` and `ogc-rs`:
- https://github.com/knarkzel/ogc-engine/tree/master/examples
- https://github.com/knarkzel/ogc-rs/tree/master/examples

**Comment by TheTechRobo** [comment]
Was rogue turned into "chase"? Don't have time to test

**Comment by lambdachad** [comment]
Rogue was just a project for testing. But chase is the most "feature complete" game thus far.

**Comment by TheTechRobo** [comment]
Thanks for the quick answer!
