### ISSUE TITLE
Missing `mp3-decoder` / any kind of audio decoders in pure no-std rust

### ISSUE THREAD

**Issue by lambdachad** [knarkzel/ogc-engine#4]
Currently, I'm unable to find any pure no-std audio decoders that I can use for the `asnd` part of `ogc-rs` library. Are there any good ones I'm not finding? In the case that there simply aren't any decoders yet, it would be a good idea to see if we can use the [minimp3](https://github.com/lieff/minimp3) library, or anything like it.

**Comment by lieff** [comment]
Hi)
For pure rust there https://github.com/Herschel/puremp3, not sure if it can be used for no-std.
For no-std minimp3 bindings there https://github.com/viriuwu/rmp3 .

**Comment by lambdachad** [comment]
Thanks for the suggestions. It seems very doable with either of those crates!

**Comment by lambdachad** [comment]
Some very useful information on what kind of audio format `asnd` supports: https://wiibrew.org/wiki/Asndlib#Audio_Format. It seems like
we can either use the cross platform `sox` tool to convert various audio formats. "The primary audio format accepted by asndlib is 16-bit, 2-channel (stereo), big-endian RAW PCM.", and to convert we can use `sox` like so:
```bash
sox input.wav -t raw -b 16 --endian big -c 2 output.raw
```
Alternatively we can do this at runtime by for instance wrapping `sox` to be callable from Rust or decoding ourselves.
